### ISSUE TITLE
有些音乐无法获取播放地址

### ISSUE THREAD

**Issue by vhikd** [winterssy/mxget#2]
有些音乐无法获取播放地址 大佬求更新

**Comment by winterssy** [comment]
没有播放地址就是不支持下载，你得叫音乐平台那边更新API，这不是我能解决的。另外，注意反馈问题的有效方式：[提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md)
