### ISSUE TITLE
可以使用的api服务能出一个列表吗？

### ISSUE THREAD

**Issue by luoqiz** [winterssy/mxget#6]
可以使用的api服务能出一个列表吗？ 例如获取酷我音乐的排行榜等接口服务。能下载无损音乐吗？

**Comment by winterssy** [comment]
可用的 API 服务在 [api.proto](https://github.com/winterssy/mxget/blob/master/api/grpc/api.proto) 定义，本项目不提供获取排行榜等接口，不能下载无损。
